paths:
  # Thresholds for the element search; see that file.
  search_params: "search_params.yaml"
  genomes_dir: "data/genomes"
  results_dir: "results"

execution:
  conda_env: "envs/IE_finder.yaml"

annotate:
  all_candidates: false

pfam_profiles:
  - "pfam/PF00589.hmm"
  - "pfam/PF22022.hmm"
